server:
  port: 80  #服务器默认端口，不需要显式指定
spring:
  application:
    name: zuul-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://140.143.56.233:8901/eureka/
#  instance: #注册在eureka的服务使用ip+port的形式出现在eureka中
#    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
# 不自定义使用默认路由规则
# 规则：http://zuul_host:zuul_port/微服务在Eureka上的serviceId/**会被转发到serviceId对应的微服务上
# 当前项目就是：http://localhost/serviceId/***   省略80端口是，因为服务器默认开放端口是80

#自定义路由规则
#zuul:
#  routes:
#    hello:
#      path: /hello/**
#      serviceId: pastime-web # 多个id用逗号隔开，实现集群
