server:
  port: 8902

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shaorensheng/configcenter.git
          default-label: master
          username: shaorensheng
          password: sheng0903
  profiles:
    active: local


---
#本地环境
spring:
  profiles: local

eureka:
  client:
    serviceUrl:
      defaultZone: http://140.143.56.233:8901/eureka/
